### ISSUE TITLE
Make memfd dependency optional

### ISSUE THREAD

**Issue by XVilka** [novafacing/cannonball#1]
To allow writing Rust TCG plugins also on macOS and Windows platforms, see https://github.com/novafacing/memfd-exec/issues/1

**Comment by novafacing** [comment]
Happy to take a PR for this once you have one ready, pretty good idea to put memfd behind a feature given that it is only used here in the examples. Otherwise, it'll be a few days before I get around to it but I'll make this change myself at some point :)

**Comment by novafacing** [comment]
This should be resolved now, `memfd` was never actually a dependency of `cannonball` but it was a dependency of the example programs.
