### ISSUE TITLE
to get qemu_plugin_outs to work you need `-d plugin` on qemu cli.

### ISSUE THREAD

**Issue by tocklime** [novafacing/cannonball#2]
https://github.com/novafacing/cannonball/blob/008f1c1afdc928af183c229e43cd5be48086a027/docs/PLUGIN_API.md?plain=1#L30

Not really an issue, but to answer your question, qemu_plugin_outs seems to output on the `plugin` log item, so you need `-d plugin` on the command line.

**Comment by novafacing** [comment]
Nice, thanks for the note! Not sure how I missed it :)
