### ISSUE TITLE
compile error: thread 'main' panicked at '"qemu_info_t_struct_

### ISSUE THREAD

**Issue by Blameying** [novafacing/cannonball#3]
Hi there, thank you for your great work! This tool is really helpful.

I found that when I try to cargo build with Cannonball, the compiler reports a panic like below:

thread 'main' panicked at '"qemu_info_t_struct_(unnamed_at_/home/xxx/target/debug/build/cannonball-6e02cc1f64a0c3b4/out/qemu-plugin_h_68_5)" is not a valid Ident', /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.69/src/fallback.rs:817:9

This error is caused by the combination of bindgen < 0.62 and Clang > 16, which was fixed in bindgen 0.62.0 version, maybe we can just update the bind dependencies to fix this.

**Comment by Blameying** [comment]
Here is the patch request: [https://github.com/novafacing/cannonball/pull/4](https://github.com/novafacing/cannonball/pull/4)

hope it is helpful.

**Comment by novafacing** [comment]
Great thanks for fixing this!
