### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by tocklime** [novafacing/cannonball#5]
QEMU master branch has support for windows plugins now. I'd like to be able to use this crate on Windows, to build plugin DLLs, but there's a few wrinkles in the way:

1. Building QEMU on windows is possible, but only in an MSYS environment. The qemu crate is not designed to build on Windows and makes heavy use of memfd, which (afaik) will never work on Windows.
2. On Windows in addition to the qemu-plugin.h, there needs to be a (built) libqemu_api_plugin.a delaylib archive to link plugins against.
3. Cannonball will need a delaylink hook exposed, similar to [this one](https://gitlab.com/qemu-project/qemu/-/blob/master/contrib/plugins/win32_linker.c?ref_type=heads)

I'm not sure what the best way to go on this is (and I understand if you don't think it's worth the effort). I'm going to try removing the dependency on qemu and getting the necessary files from somewhere else (checked in files? download published binaries?)

**Comment by novafacing** [comment]
I've been meaning for a while to move this crate to the method I use for a newer bindings crate I've been working on, https://github.com/novafacing/yices2-rs, which uses the method you described (vendored source in a tarball extracted and built in build.rs). Maybe that would work here? I'm totally ok with the idea, and happy for you to give it a go (I'm unfortunately too busy, probably for the rest of the year 😭).

QEMU sources are quite big, my preference for the large files is LFS personally but I'm open to suggestions.

**Comment by tocklime** [comment]
Fundamentally, the cannonball library only needs qemu_plugin.h and qemu_plugin_api.lib to build a .dll file that can be used as a plugin. The examples need the qemu_rs crate to do the 'embedding the whole qemu binary' thing, but I'm not so interested in that.

Options:

1. Embed whole source (you're right, unpleasantly big). Could be a git submodule?
2. Download source (this is what it does now, I guess), but maybe without (all) the building.
3. Download binary and extract header and qemu_plugin_api.lib (once qemu 8.2 gets released).
4. Store just header and qemu_plugin_api.lib in cannonball (ok, but how to update it? do that when? manually?)

I'm toying around with number 4 at the moment. Mostly because it's easiest to get started. I'll have a go and let you know where I get up to.

**Comment by novafacing** [comment]
Windows should work with the [qemu-plugin](https://github.com/novafacing/qemu-rs) crate. I'm deprecating this crate in favor of that one, as it's just all around much better code. All the good stuff from here is there, and there's no junk to get in the way.
